# Generated by Django 4.2 on 2023-04-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movieorder'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pivot_table',
            field=models.ManyToManyField(related_name='users', through='movies.MovieOrder', to='movies.movie'),
        ),
    ]
